version: '3'
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - mongo-server
  mongo-server: 
    image: 'mongo'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: guestbookdb
    ports:
      - "27017:27017"